apiVersion: apps/v1
kind: Deployment
metadata:
  name: raje-deployment
  labels:
    app: miniproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miniproject
  template:
    metadata:
      labels:
        app: miniproject
    spec:
      containers:
      - name: miniproject
        image: satarkar424/raje
        ports:
        - containerPort: 3000